### ISSUE TITLE
Compatability with custom day/night times?

### ISSUE THREAD

**Issue by vhcrack** [hyperdefined/TimeBar#13]
I was wondering if there is compatibility with custom lengths for day/night (namely **RealisticSeasons**).

And I was also wondering if there was an option to use numerical times like 7:00 AM instead of Night/Day/Dawn/Dusk etc.

**Comment by hyperdefined** [comment]
I could add support for changing when the "times" are. They are hardcoded, but I can easily add configuration options for them.

They are ranges, here is the code section:
```java
if (time >= 23000) {
     title = parseString(config.getString("times.dawn"));
}
if (time >= 0 && time < 6000) {
    title = parseString(config.getString("times.morning"));
}
if (time >= 6000 && time < 9000) {
    title = parseString(config.getString("times.noon"));
}
if (time >= 9000 && time < 12000) {
    title = parseString(config.getString("times.afternoon"));
}
if (time >= 12000 && time < 14000) {
    title = parseString(config.getString("times.sunset"));
}
if (time >= 14000 && time < 18000) {
    title = parseString(config.getString("times.night"));
}
if (time >= 18000 && time < 23000) {
    title = parseString(config.getString("times.midnight"));
}
```
Would you want to be able to change these options? Like setting each range?

I could add support for a numerical time instead, I would have to calculate that directly but it is possible.

**Comment by vhcrack** [comment]
> I could add support for changing when the "times" are. They are hardcoded, but I can easily add configuration options for them.
> 
> They are ranges, here is the code section:
> ```java
> if (time >= 23000) {
>      title = parseString(config.getString("times.dawn"));
> }
> if (time >= 0 && time < 6000) {
>     title = parseString(config.getString("times.morning"));
> }
> if (time >= 6000 && time < 9000) {
>     title = parseString(config.getString("times.noon"));
> }
> if (time >= 9000 && time < 12000) {
>     title = parseString(config.getString("times.afternoon"));
> }
> if (time >= 12000 && time < 14000) {
>     title = parseString(config.getString("times.sunset"));
> }
> if (time >= 14000 && time < 18000) {
>     title = parseString(config.getString("times.night"));
> }
> if (time >= 18000 && time < 23000) {
>     title = parseString(config.getString("times.midnight"));
> }
> ```
> Would you want to be able to change these options? Like setting each range?
> 
> I could add support for a numerical time instead, I would have to calculate that directly but it is possible.

A numerical time option would be great actually, you could use config options to mess around with the format for {time} with options such as a 12-hour (12:00 AM), 24-hour (00:00) or "phases" (what is currently the time format) format.

But, the thing about RealisticSeasons is that the amount of time in the day/night is dependent on the current month. It changes every 28-31 days and [can range from 7 minutes in the day to 13 minutes in the night](https://wiki.realisticseasons.com/calendar/day-and-night-length) to the opposite of that. So it's really a specific compatibility issue.

**Comment by hyperdefined** [comment]
I'll look into supporting this plugin soon. They have an API which I can use to get which season the world is in, along with the time (they track time differently).

I have an idea of what I could do, I'll start working on it.

**Comment by vhcrack** [comment]
Sure! I'd love a test version to see if it works.

**Comment by hyperdefined** [comment]
[timebar-1.2-RS-TEST.zip](https://github.com/hyperdefined/TimeBar/files/8970742/timebar-1.2-RS-TEST.zip)

Can't attach jar files, so I put it into a zip file.

I'm not too familiar with RealisticSeasons, so please let me know if the time and stuff works correctly!

Things to note:
-  The will be a new configuration file called `realisticseasons.yml` in the `TimeBar` folder. This will override most options in the other default configuration file.
- In the new configuration file, you can determine when each "time of day" occurs for each season.
- I added support for showing the numerical time. This time reads directly from RealisticSeasons, so it will match. Make sure to read the `timebar-title` in the new configuration for placeholders. The default title will show all.

If anything is not right, or if you have a feature that I missed to support this plugin, please let me know!

**Comment by vhcrack** [comment]
Everything seems to work pretty well so far, but, there's an issue. The difference in day/night time is dependent on the month, not the season it currently is. Only issue I'm seeing so far.

**Comment by hyperdefined** [comment]
I see, I completely misunderstood what you told me. I can go ahead and redo that, oops!

**Comment by vhcrack** [comment]
24h format is still showing even if false in realisticseasons.yml, other than that it's good!

**Comment by hyperdefined** [comment]
I had the logic flipped for that config option, it is now fixed.

I will go ahead and release a proper version soon, make sure to update to that version once it is out! I will go ahead and close this issue once it's out.

**Comment by hyperdefined** [comment]
I released an update for this now, please go ahead and update! Make sure to delete your configs as they have changed again. Thank you for the suggestion and helping me test! This plugin is awesome and I am glad I bought it to test.

https://github.com/hyperdefined/TimeBar/releases/tag/1.3
