### ISSUE TITLE
Configuration suggestions

### ISSUE THREAD

**Issue by CleMooling** [hyperdefined/TimeBar#18]
I hope the Timebar function can be enabled automatically for every players and then they can disable it for themselves by their own. 
So I hope you can add a setting in the config.yml that make the Timebar function default, and players no longer need to enable it. 
I hope you can reply this as soon as possible. 
Your plugin is very useful, thanks for your efforts!
(My English is not very well, if you have any other questions you can ask me immediately. )

**Comment by hyperdefined** [comment]
The plugin will automatically enable for all players. You can use `/timebar on` or `/timebar off` to enable or disable.

**Comment by CleMooling** [comment]
But before the player uses the command "/timebar on", the Timebar will not be displayed.&nbsp;
I mean I want the Timebar can be displayed for everyone automatically without players use the command to make it shown in their screens.&nbsp;
If you need more information, I can record a video to explain this case.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 22, 2022 07:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hyperdefined/TimeBar] Configuration suggestions (Issue #18)




 
The plugin will automatically enable for all players. You can use /timebar on or /timebar off to enable or disable.

**Comment by hyperdefined** [comment]
As I said, the plugin will automatically turn it on for players when they join. I would double check your config for the plugin, and make sure you have your worlds set correctly. It enables fine for me on join on a fresh server.

A video would help to, along with your config file for the plugin.
