### ISSUE TITLE
EU Date support 

### ISSUE THREAD

**Issue by 3dwardify** [hyperdefined/TimeBar#22]
Would it be possible to add other date formats into the config?

**Comment by xAetheris** [comment]
Did you get yours to work?

**Comment by xAetheris** [comment]
Mine doesn't seem to work.

**Comment by hyperdefined** [comment]
> Would it be possible to add other date formats into the config?

Yes, I can add support for different date formats.

**Comment by hyperdefined** [comment]
This will be added in the next version (1.3.4).
