### ISSUE TITLE
TimeBar not working in specified world

### ISSUE THREAD

**Issue by xAetheris** [hyperdefined/TimeBar#23]
Hello, I’m currently trying to enable the timebar in my server, but whenever I try to enable it, it shows it’s been enabled but nothing appears.

My server currently runs 1.19.2.

**Comment by xAetheris** [comment]
![Screenshot 2023-01-16 140928](https://user-images.githubusercontent.com/121515303/212750869-94f72355-c864-435d-8610-158ab99e9045.png)

I tried to switch the times to a 12-hour format. But this is what shows up now, I have a Bungee network but I installed the TimeBar directly into my Survival server, the overworld name is "Survival"

**Comment by hyperdefined** [comment]
That is very strange... did you edit the times under `realisticseasons.yml` file in the `TimeBar` folder? I just tried it myself on a fresh 1.19.2 server, and it's working fine for me.

**Comment by xAetheris** [comment]
> That is very strange... did you edit the times under `realisticseasons.yml` file in the `TimeBar` folder? I just tried it myself on a fresh 1.19.2 server, and it's working fine for me.

Yes I did. Was I not supposed to?

**Comment by xAetheris** [comment]
> working

I basically changed the times from 24-hour format to 12-hour format, such as (16:00 - 04:00)

**Comment by hyperdefined** [comment]
Those times are for RealisticSeasons only. Those you really shouldn't mess with unless you want to change what each time of day is (dawn, morning, afternoon, etc).

The first config at the top (`use-24h-format`) can let you change the display of the time on the title. What were you trying to do originally?

Yes, you can delete the `realisticseasons.yml` file and restart your server, it will automatically recreate it.

**Comment by xAetheris** [comment]
> Those times are for RealisticSeasons only. Those you really shouldn't mess with unless you want to change what each time of day is (dawn, morning, afternoon, etc). If you wish to change the durations, you can, just make sure to use 24 hour time. I probably should put that in the config so it's more clear.
> 
> The first config at the top (`use-24h-format`) can let you change the display of the time on the title. What were you trying to do originally?
> 
> Yes, you can delete the `realisticseasons.yml` file and restart your server, it will automatically recreate it.

I just re-installed the plugin, haven't messed with the config yet besides the `world-to-track-time` and `worlds-to-show-in`. The TimeBar doesn't want to show up.

**Comment by xAetheris** [comment]
I executed `/timebar reload` and `/timebar on` and nothing happens besides sending a confirmation message.

**Comment by xAetheris** [comment]
Maybe a plugin is preventing it from showing?

**Comment by xAetheris** [comment]
`# Set which world will TimeBar show the time for.
world-to-track-time: "Survival"

# Set which worlds the TimeBar will show in.
worlds-to-show-in:
  - "Survival"

# Set the color of the TimeBar.
# The valid options are: blue, green, pink, purple, red, white, and yellow.
titlebar-color: "blue"

# Set the text of the TimeBar.
# {TIME} - The time to display. Dawn, afternoon, etc.
# {DAYCOUNT} - How many total days in game have passed.
timebar-title: "{TIME} (Day {DAYCOUNT})"

# How often should the title and progress update?
# This is in game ticks, 20 ticks = 1 second.
bar-update-frequency: 20

# Want to change the wording of the times?
times:
  dawn: "Dawn"
  morning: "Morning"
  noon: "Noon"
  afternoon: "Afternoon"
  sunset: "Sunset"
  night: "Night"
  midnight: "Midnight"

# Set when each time of day is shown.
# This is in game ticks. You can see by using "/time query daytime"
# When the ticks hit one of these, it will be that time of day.
times-of-day:
  dawn: 23000
  morning: 1000
  noon: 6000
  afternoon: 10500
  sunset: 12250
  night: 13800
  midnight: 18000

# No touch please :)
config-version: 3`

This is my `config.yml`.

`# Use 24hr format for times.
use-24h-format: false

# Set the text of the TimeBar.
# {TIME} - The current world time, 7:20 am, etc.
# {TIME-WORD} - The time to display. Dawn, afternoon, etc.
# {DAYCOUNT} - How many total days in game have passed.
# {SEASON} - The current season.
# {DATE} - The current date.
timebar-title: "{TIME} - {TIME-WORD} ({DATE}) - {SEASON}"

# Want to change the wording of the time of days?
times:
  dawn: "Dawn"
  morning: "Morning"
  noon: "Noon"
  afternoon: "Afternoon"
  sunset: "Sunset"
  night: "Night"
  midnight: "Midnight"

# Set each "time of day" for each month.
# When the time hits one of these, it will turn that "time of day."
# Example: January at 7:45 AM. It will be dawn.
month:
  january:
    dawn: "06:00"
    morning: "08:30"
    noon: "12:00"
    afternoon: "15:00"
    sunset: "16:30"
    night: "18:30"
    midnight: "00:00"
  february:
    dawn: "05:25"
    morning: "08:00"
    noon: "12:00"
    afternoon: "15:35"
    sunset: "17:00"
    night: "18:50"
    midnight: "00:00"
  march:
    dawn: "05:00"
    morning: "07:30"
    noon: "12:00"
    afternoon: "16:00"
    sunset: "17:45"
    night: "19:15"
    midnight: "00:00"
  april:
    dawn: "04:30"
    morning: "07:00"
    noon: "12:00"
    afternoon: "16:30"
    sunset: "18:20"
    night: "19:45"
    midnight: "00:00"
  may:
    dawn: "04:00"
    morning: "06:30"
    noon: "12:00"
    afternoon: "17:00"
    sunset: "18:55"
    night: "20:05"
    midnight: "00:00"
  june:
    dawn: "03:35"
    morning: "06:00"
    noon: "12:00"
    afternoon: "17:30"
    sunset: "19:30"
    night: "20:30"
    midnight: "00:00"
  july:
    dawn: "03:10"
    morning: "05:30"
    noon: "12:00"
    afternoon: "18:00"
    sunset: "20:00"
    night: "21:00"
    midnight: "00:00"
  august:
    dawn: "03:35"
    morning: "06:00"
    noon: "12:00"
    afternoon: "17:30"
    sunset: "19:30"
    night: "20:30"
    midnight: "00:00"
  september:
    dawn: "04:00"
    morning: "06:30"
    noon: "12:00"
    afternoon: "17:00"
    sunset: "18:55"
    night: "20:05"
    midnight: "00:00"
  october:
    dawn: "04:30"
    morning: "07:00"
    noon: "12:00"
    afternoon: "16:30"
    sunset: "18:20"
    night: "19:45"
    midnight: "00:00"
  november:
    dawn: "05:00"
    morning: "07:30"
    noon: "12:00"
    afternoon: "16:00"
    sunset: "17:45"
    night: "19:15"
    midnight: "00:00"
  december:
    dawn: "05:30"
    morning: "08:00"
    noon: "12:00"
    afternoon: "15:35"
    sunset: "17:00"
    night: "18:50"
    midnight: "00:00"

# No touch please :)
config-version: 1`

This is my `realisticseasons.yml`, my survival world is named "Survival", nothing seems to work at this point.

**Comment by xAetheris** [comment]
```test```

**Comment by xAetheris** [comment]
![Screenshot 2023-01-18 125405](https://user-images.githubusercontent.com/121515303/213257638-c17439f5-0cc6-4779-bdbb-a8268761a98e.png)
![Screenshot 2023-01-18 125420](https://user-images.githubusercontent.com/121515303/213257641-71eeb991-81c4-46c4-ba61-ac659632c241.png)

**Comment by xAetheris** [comment]
I'm getting this error now, `[17:46:25 ERROR]: [TimeBar] Cannot retrieve date from RealisticSeasons!`

**Comment by xAetheris** [comment]
Got it to finally work.

**Comment by hyperdefined** [comment]
Sorry for the delayed response again, had classes today.

I never tested the plugin with Multiverse, so it could of been that possibly. I can try to see if I can improve that compatibility.

**Comment by hyperdefined** [comment]
I was correct, there were problems with using the reload command. This has been fixed so you can use `/timebar reload` correctly now (the bossbar would not appear when you changed worlds via config).

**Comment by xAetheris** [comment]
Thank you for helping me, for future reference, ask players if they're using Lunar Client because the boss bar feature is disabled by default when Lunar Client is installed. So prompt them to enable it through Lunar Options! :) Hope this helps.

**Comment by xAetheris** [comment]
The main cause of my issue was Lunar Client disabling the BossBar feature.
