### ISSUE TITLE
TimeBar - RealisticSeasons Error

### ISSUE THREAD

**Issue by Jaaamii** [hyperdefined/TimeBar#24]
[ERROR]: [TimeBar] Cannot retrieve date from RealisticSeasons!

1.19.3 PaperMC
What does this mean and how do I fix it?

**Comment by Jaaamii** [comment]
Okay turns out I had to actually start the season cycle for the timer bar to work

**Comment by hyperdefined** [comment]
Yeah that message is thrown when TimeBar can't get the date from the world. 99% of the time RS just hasn't been setup for that world, resulting in it not having a date.

I should improve that message in the future, so users can better understand how to fix it.
