### ISSUE TITLE
RealisticSeason configuration does not load upon startup. 

### ISSUE THREAD

**Issue by RealisticThreat** [hyperdefined/TimeBar#28]
Hello, everytime when I restart the server, RealisticSeason's timebar configuration does not load. It always resets me back to "Time (Day Number". I have to run /timebar reload for it to load my RealisticSeason's configuration again. 

The configuration I have in realisticseasons.yml is "timebar-title: "{SEASON} {TIME-WORD}: {TIME}"

But I always get this after server startup:
![image](https://user-images.githubusercontent.com/69768653/224518108-308f6ae8-3b64-482a-814c-b48b98c2f358.png)

**Comment by hyperdefined** [comment]
First, what server software are you using (Paper/Spigot/etc) and version? When you start your server, does TimeBar say this?
```
[16:09:20 INFO]: [TimeBar] Enabling TimeBar v1.3.4
[16:09:21 INFO]: [TimeBar] RealisticSeasons is detected! Enabling support.
[16:09:21 INFO]: [TimeBar] Starting new TimeBar task with RealisticSeasons support...
```

Or does this only appear after you use the reload command? Are there any other messages from my plugin?

I've just tested this on a brand new 1.19.3 Paper server (build 448) and do not experience this.

**Comment by RealisticThreat** [comment]
I am using Paper version git-Paper-426 (MC: 1.19.3) 

These lines do not appear upon server startup but they do only appear when I use the reload command:
[16:09:21 INFO]: [TimeBar] RealisticSeasons is detected! Enabling support.
[16:09:21 INFO]: [TimeBar] Starting new TimeBar task with RealisticSeasons support...

I also noticed that "Enabling TimeBar" comes before "Enabling RealisticSeasons" on server startup.

**Comment by hyperdefined** [comment]
That is very strange... I just tested again with your exact same version, and RealisticSeasons loads first for me. Are you using the latest version of TimeBar?

**Comment by RealisticThreat** [comment]
Yes, and the latest version of RealisticSeasons. Is there a way to have the Timebar plugin wait till RealisticSeasons loads and then load?

**Comment by hyperdefined** [comment]
It should be doing that already (see https://github.com/hyperdefined/TimeBar/blob/master/src/main/resources/plugin.yml#L8). I defined RealisticSeasons to be a softdepend, which means TimeBar should load after it. That's very strange to see that it's not working on your end. There's no other way for me "delay" loading besides that. I've never seen it do this before.

**Comment by RealisticThreat** [comment]
Oh, it is fixed now Thanks.

**Comment by hyperdefined** [comment]
Thanks for letting me know. Not sure what it was or what caused it.
