### ISSUE TITLE
{DAY} uses the wrong value.

### ISSUE THREAD

**Issue by 4ebyrek99** [hyperdefined/TimeBar#33]
I made my translation for the days of the week and I have an error, an example is a day that is Wednesday in realisticSeasons, and {DAY} takes Saturday. Is it just my problem or not?

**Comment by hyperdefined** [comment]
Can you show me your `realisticseasons.yml` config from TimeBar?

**Comment by 4ebyrek99** [comment]
[realisticseasons.zip](https://github.com/hyperdefined/TimeBar/files/11658850/realisticseasons.zip)

**Comment by 4ebyrek99** [comment]
![Screenshot_2](https://github.com/hyperdefined/TimeBar/assets/85881759/084c974a-4de3-415b-ba15-47f2733aea52)

**Comment by hyperdefined** [comment]
I believe this is some inconsistencies with how I get the date from RealisticSeasons. I'll try to write a fix and send a test version of the plugin.

**Comment by hyperdefined** [comment]
Looking further into this, it looks like RS calculates day and month differently than I thought. I will have to ask the developer to add an easy way to get the day of week and month.

**Comment by 4ebyrek99** [comment]
Thanks for the info, I will wait for the update.

**Comment by hyperdefined** [comment]
This has been fixed on the latest version: https://github.com/hyperdefined/TimeBar/releases/tag/1.3.6

Please make sure to update RealisticSeasons to version 10.5.1, as it added new API.
