### ISSUE TITLE
Add color support for bar title & different bar color for each season

### ISSUE THREAD

**Issue by awakcon1234** [hyperdefined/TimeBar#61]
Please add support for minecraft formatting codes `(&1, &2, &a, &b, &o)` and hex color code `(&#91cfff)` to be displayable in the bossbar's title, and add configuration to change the bar's color based on current season.

Everything else is perfect! Thank you for this really awesome plugin!

**Comment by hyperdefined** [comment]
The plugin doesn't use those formatting codes, it uses a different system that is modern. It uses MiniMessage, which you can see a visualizer here: https://webui.advntr.dev/

For changing the bar's color based on season, I can probably add that.

**Comment by awakcon1234** [comment]
Perfect! I didn't notice the usage of MiniMessage in the wiki 😅, maybe a small comment about MiniMessage formatting and update the default configuration files will make sure others won't come up like me.

**Comment by hyperdefined** [comment]
Hello, I added this to the latest version: https://github.com/hyperdefined/TimeBar/releases/tag/1.4.4 Please update for this feature!

Please delete your /plugins/TimeBar/reaslisticseasons.yml file before updating. You will see the new colors section to change based on the month.
