### ISSUE TITLE
Invalid month with RealisticSeasons

### ISSUE THREAD

**Issue by hugohuetzel** [hyperdefined/TimeBar#62]
The tag "{MONTH}" shows as "INVALID" in the time bar with RealisticSeasons.

**Comment by hyperdefined** [comment]
Can you provide your realisticseasons.yml file? You should see something in the console about this, please send it over.

**Comment by hugohuetzel** [comment]
Here ist the realisticseasons.yml (renamed to txt for upload):
[realisticseasons.yml](https://github.com/user-attachments/files/16407399/realisticseasons.yml.txt)

Could it be because the months are translated into RealisticSeasons?
[calendar.yml](https://github.com/user-attachments/files/16407460/calendar.yml.txt)

**Comment by hyperdefined** [comment]
That would be the issue, I would suggest making this change: change the `january` to the translated version in all lower case. Do this for all the months.
```
january: # change this to be just januar
    name: "Januar"
    dawn: "06:00"
    morning: "08:30"
    noon: "12:00"
    afternoon: "15:00"
    sunset: "16:30"
    night: "18:30"
    midnight: "00:00"
 ```

**Comment by hugohuetzel** [comment]
With this change i will get this error spam:
[07:44:15 ERROR]: [TimeBar] Section month.december does NOT EXIST!

**Comment by hyperdefined** [comment]
I fixed this issue. You can use the original config you sent, that one will work now. Please update: https://github.com/hyperdefined/TimeBar/releases/tag/1.4.4
